/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/uploads/scene.gltf -T -t -o model.tsx 
Files: ./public/models/uploads/scene.gltf [100.2KB] > C:\Users\Константин\Documents\page\JavaScript\React\My\vite-3d-store\scene-transformed.glb [1.53MB] (-1430%)
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/barbie-dodge-pickup-custom-longcar-by-alexka-f11e42bb15b543c880be9a0b824dfd51
Title: 💗Barbie Dodge Pickup Custom LongCar by Alex.Ka.
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
  }
  materials: {
    ALs_CARS: THREE.MeshPhysicalMaterial
    BARBIE: THREE.MeshPhysicalMaterial
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    barbie_front: THREE.MeshPhysicalMaterial
    barbie_rear: THREE.MeshPhysicalMaterial
    barbie_side: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    bottom: THREE.MeshStandardMaterial
    carshadow: THREE.MeshStandardMaterial
    dodge_rim_sticker_MATTE: THREE.MeshStandardMaterial
    floor: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    pink_carbon: THREE.MeshPhysicalMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    plate: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
    texture_1_INT_EMB: THREE.MeshPhysicalMaterial
    texture_1_INT_MATTE: THREE.MeshStandardMaterial
    texture_1_PLAYBOY: THREE.MeshPhysicalMaterial
    texture_1_chrome: THREE.MeshStandardMaterial
    texture_1_radiator: THREE.MeshStandardMaterial
    texture_2_CHROME: THREE.MeshStandardMaterial
    texture_2_INT_UP: THREE.MeshStandardMaterial
    texture_2_MATTE: THREE.MeshStandardMaterial
    texture_2_brakedisc: THREE.MeshStandardMaterial
    texture_3_brakelights: THREE.MeshStandardMaterial
    texture_3_headlights: THREE.MeshStandardMaterial
    texture_3_sidemirrors: THREE.MeshStandardMaterial
    texture_4_RIM_chrome: THREE.MeshStandardMaterial
    texture_4_foglights: THREE.MeshStandardMaterial
    tire_left_L: THREE.MeshStandardMaterial
    tire_protector: THREE.MeshStandardMaterial
    tire_right_R: THREE.MeshStandardMaterial
    tire_right_RIM_BOLTS: THREE.MeshStandardMaterial
    window_glass: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.ALs_CARS} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.BARBIE} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.barbie_front} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.barbie_rear} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.barbie_side} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.bottom} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.carshadow} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.dodge_rim_sticker_MATTE} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.floor} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial005} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.pink_carbon} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.PaletteMaterial006} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.plate} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial007} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.texture_1_INT_EMB} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.texture_1_INT_MATTE} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.texture_1_PLAYBOY} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.texture_1_chrome} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.texture_1_radiator} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.texture_2_CHROME} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.texture_2_INT_UP} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.texture_2_MATTE} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.texture_2_brakedisc} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.texture_3_brakelights} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.texture_3_headlights} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.texture_3_sidemirrors} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.texture_4_RIM_chrome} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.texture_4_foglights} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.tire_left_L} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.tire_protector} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.tire_right_R} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.tire_right_RIM_BOLTS} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.window_glass} rotation={[-Math.PI / 2, 0, 0]} scale={1.111} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
